In [ ]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [ ]:
data_url = 'https://raw.githubusercontent.com/mli/ag-docs/main/knot_theory/'
train_data = TabularDataset(f'{data_url}train.csv')
train_data.head()

In [ ]:
label = 'signature'
train_data[label].describe()

In [ ]:
import os

cpu_count = os.cpu_count()
print(f"Number of CPUs: {cpu_count}")

In [ ]:
predictor = TabularPredictor(label=label).fit(train_data,
                                              num_gpus=1)

In [ ]:
test_data = TabularDataset(f'{data_url}test.csv')

y_pred = predictor.predict(test_data.drop(columns=[label]))
y_pred.head()

In [ ]:
predictor.evaluate(test_data, silent=True)

In [ ]:
predictor.leaderboard(test_data)

# Text

In [42]:
%matplotlib inline

import numpy as np
import warnings
import matplotlib.pyplot as plt

warnings.filterwarnings('ignore')
np.random.seed(123)

In [43]:
from autogluon.core.utils.loaders import load_pd
train_data = load_pd.load('https://autogluon-text.s3-accelerate.amazonaws.com/glue/sst/train.parquet')
test_data = load_pd.load('https://autogluon-text.s3-accelerate.amazonaws.com/glue/sst/dev.parquet')
subsample_size = 1000  # subsample data for faster demo, try setting this to larger values
train_data = train_data.sample(n=subsample_size, random_state=0)
train_data.head(10)

Loaded data from: https://autogluon-text.s3-accelerate.amazonaws.com/glue/sst/train.parquet | Columns = 2 / 2 | Rows = 67349 -> 67349
Loaded data from: https://autogluon-text.s3-accelerate.amazonaws.com/glue/sst/dev.parquet | Columns = 2 / 2 | Rows = 872 -> 872

,sentence,label
43787,very pleasing at its best moments,1
16159,", american chai is enough to make you put away the guitar , sell the amp , and apply to medical school .",0
59015,too much like an infomercial for ram dass 's latest book aimed at the boomer,0
5108,a stirring visual sequence,1
67052,cool visual backmasking,1
35938,hard ground,0
49879,"the striking , quietly vulnerable personality of ms. ambrose",1
51591,"pan nalin 's exposition is beautiful and mysterious , and",1
56780,wonderfully loopy,1
28518,"most beautiful , evocative",1

In [109]:
data = load_pd.load("data/spotify.parquet")
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

subsample_size = 5000  # subsample data for faster demo, try setting this to larger values
train_data = train_data.sample(n=subsample_size, random_state=0)

Loaded data from: data/spotify.parquet | Columns = 18 / 18 | Rows = 41099 -> 41099

In [110]:
data

,name,artist,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,chorus_hit,sections,target
0,Jealous Kind Of Fella,Garland Green,0.417,0.620,3,-7.727,Major,0.0403,0.4900,0.000000,0.0779,0.8450,185.655,173533.0,3,32.94975,9,1
1,Initials B.B.,Serge Gainsbourg,0.498,0.505,3,-12.475,Major,0.0337,0.0180,0.107000,0.1760,0.7970,101.801,213613.0,4,48.82510,10,0
2,Melody Twist,Lord Melody,0.657,0.649,5,-13.392,Major,0.0380,0.8460,0.000004,0.1190,0.9080,115.940,223960.0,4,37.22663,12,0
3,Mi Bomba Sonó,Celia Cruz,0.590,0.545,7,-12.058,Minor,0.1040,0.7060,0.024600,0.0610,0.9670,105.592,157907.0,4,24.75484,8,0
4,Uravu Solla,P. Susheela,0.515,0.765,11,-3.515,Minor,0.1240,0.8570,0.000872,0.2130,0.9060,114.617,245600.0,4,21.79874,14,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41094,Lotus Flowers,Yolta,0.172,0.358,9,-14.430,Major,0.0342,0.8860,0.966000,0.3140,0.0361,72.272,150857.0,4,24.30824,7,0
41095,Calling My Spirit,Kodak Black,0.910,0.366,1,-9.954,Major,0.0941,0.0996,0.000000,0.2610,0.7400,119.985,152000.0,4,32.53856,8,1
41096,Teenage Dream,Katy Perry,0.719,0.804,10,-4.581,Major,0.0355,0.0132,0.000003,0.1390,0.6050,119.999,227760.0,4,20.73371,7,1
41097,Stormy Weather,Oscar Peterson,0.600,0.177,7,-16.070,Major,0.0561,0.9890,0.868000,0.1490,0.5600,120.030,213387.0,4,21.65301,14,0
41098,Dust,Hans Zimmer,0.121,0.123,4,-23.025,Minor,0.0443,0.9640,0.696000,0.1030,0.0297,95.182,341396.0,4,71.05343,15,0

In [111]:
train_data

,name,artist,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,chorus_hit,sections,target
35994,Come Back Song,Darius Rucker,0.516,0.745,9,-5.674,Major,0.0381,0.13800,0.000000,0.1140,0.770,177.781,235147.0,4,21.91768,10,1
9807,New Orleans,The Staple Singers,0.757,0.605,11,-11.869,Major,0.0427,0.10700,0.000476,0.0372,0.655,121.366,266307.0,4,32.71222,11,1
22905,Roadhouse Blues,Imperiet,0.554,0.911,9,-7.714,Major,0.0696,0.06190,0.000017,0.8720,0.607,127.148,248133.0,4,54.51084,11,0
11831,Fun House,The Stooges,0.521,0.745,9,-13.528,Major,0.0359,0.00364,0.000217,0.1240,0.914,131.694,465560.0,4,58.20880,19,0
30331,Gépinduló,Pokolgép,0.396,0.997,9,-5.180,Minor,0.2060,0.00287,0.883000,0.8030,0.123,162.022,287547.0,4,93.78882,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,Brother Love's Travelling Salvation Show,Neil Diamond,0.428,0.432,8,-11.580,Major,0.0288,0.57500,0.009330,0.0888,0.808,135.142,211862.0,4,33.76803,11,1
6040,Reelin' And Rockin',The Dave Clark Five,0.538,0.794,7,-8.145,Major,0.0857,0.23600,0.000003,0.0850,0.950,91.110,167360.0,4,132.19797,4,1
27775,"Burn, Don't Freeze!",Sleater-Kinney,0.304,0.968,1,-4.450,Major,0.0976,0.24400,0.000003,0.2220,0.543,162.539,200720.0,4,18.08376,12,0
8263,Little Hands,Alexander 'Skip' Spence,0.330,0.485,8,-11.396,Minor,0.0367,0.19100,0.000000,0.0682,0.506,93.219,221627.0,4,40.41514,9,0
33765,Rock Yo Hips,Crime Mob Featuring Lil Scrappy,0.847,0.667,6,-5.700,Major,0.1700,0.08690,0.000000,0.4430,0.707,77.492,226547.0,4,52.74091,8,1

In [120]:
from autogluon.multimodal import MultiModalPredictor
from autogluon.tabular.configs.hyperparameter_configs import get_hyperparameter_config
hyperparameters = get_hyperparameter_config('multimodal')
import uuid
model_path = f"./tmp/{uuid.uuid4().hex}-automm_sst"
predictor = MultiModalPredictor(label='target', eval_metric='acc')#, path=model_path)
#predictor = TabularPredictor(label='target', eval_metric='acc', path=model_path)
#predictor.fit(train_data, time_limit=180, num_gpus=1)#, hyperparameters=hyperparameters)
predictor.fit(train_data, time_limit=180)

No path specified. Models will be saved in: "AutogluonModels/ag-20240828_134101"
=================== System Info ===================
AutoGluon Version:  1.1.1
Python Version:     3.10.14
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu May 30 04:13:58 UTC 2024
CPU Count:          128
Pytorch Version:    2.2.1
CUDA Version:       11.8
Memory Avail:       450.42 GB / 503.47 GB (89.5%)
Disk Space Avail:   2936.21 GB / 49150.01 GB (6.0%)
===================================================
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [1, 0]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])

AutoMM starts to create your model. ✨✨✨

To track the learning progress, you can open a terminal and launch Tensorboard:
    ```shell
    # Assume you have installed tensorboard
    tensorboard --logdir /scratch/lgrinszt/lm_tab/AutogluonModels/ag-20240828_134101
    ```

INFO: [rank: 0] Seed set to 0
GPU Count: 1
GPU Count to be Used: 1
GPU 0 Name: Tesla V100S-PCIE-32GB
GPU 0 Memory: 3.95GB/32.0GB (Used/Total)

INFO: Using 16bit Automatic Mixed Precision (AMP)
INFO: GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:
  | Name              | Type                | Params | Mode
------------------------------------------------------------------
0 | model             | MultimodalFusionMLP | 110 M  | train
1 | validation_metric | MulticlassAccuracy  | 0      | train
2 | loss_func         | CrossEntropyLoss    | 0      | train
------------------------------------------------------------------
110 M     Trainable params
0         Non-trainable params
110 M     Total params
442.784   Total estimated model params size (MB)
INFO: SLURM auto-requeueing enabled. Setting signal handlers.

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

Validation: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 17: 'val_acc' reached 0.69000 (best 0.69000), saving model to '/scratch/lgrinszt/lm_tab/AutogluonModels/ag-20240828_134101/epoch=0-step=17.ckpt' as top 3
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

Validation: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 35: 'val_acc' reached 0.79400 (best 0.79400), saving model to '/scratch/lgrinszt/lm_tab/AutogluonModels/ag-20240828_134101/epoch=0-step=35.ckpt' as top 3
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

Validation: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 1, global step 53: 'val_acc' reached 0.83000 (best 0.83000), saving model to '/scratch/lgrinszt/lm_tab/AutogluonModels/ag-20240828_134101/epoch=1-step=53.ckpt' as top 3
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

Validation: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 1, global step 71: 'val_acc' reached 0.81000 (best 0.83000), saving model to '/scratch/lgrinszt/lm_tab/AutogluonModels/ag-20240828_134101/epoch=1-step=71.ckpt' as top 3
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

Validation: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 2, global step 89: 'val_acc' reached 0.82000 (best 0.83000), saving model to '/scratch/lgrinszt/lm_tab/AutogluonModels/ag-20240828_134101/epoch=2-step=89.ckpt' as top 3
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

Validation: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 2, global step 107: 'val_acc' reached 0.84000 (best 0.84000), saving model to '/scratch/lgrinszt/lm_tab/AutogluonModels/ag-20240828_134101/epoch=2-step=107.ckpt' as top 3
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

Validation: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 3, global step 125: 'val_acc' reached 0.83000 (best 0.84000), saving model to '/scratch/lgrinszt/lm_tab/AutogluonModels/ag-20240828_134101/epoch=3-step=125.ckpt' as top 3
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/soda/lgrinszt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
INFO: Time limit reached. Elapsed time is 0:03:00. Signaling Trainer to stop.

Validation: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 3, global step 139: 'val_acc' reached 0.83600 (best 0.84000), saving model to '/scratch/lgrinszt/lm_tab/AutogluonModels/ag-20240828_134101/epoch=3-step=139.ckpt' as top 3
Start to fuse 3 checkpoints via the greedy soup algorithm.
INFO: SLURM auto-requeueing enabled. Setting signal handlers.

Predicting: |          | 0/? [00:00<?, ?it/s]

INFO: SLURM auto-requeueing enabled. Setting signal handlers.

Predicting: |          | 0/? [00:00<?, ?it/s]

INFO: SLURM auto-requeueing enabled. Setting signal handlers.

Predicting: |          | 0/? [00:00<?, ?it/s]

AutoMM has created your model. 🎉🎉🎉

To load the model, use the code below:
    ```python
    from autogluon.multimodal import MultiModalPredictor
    predictor = MultiModalPredictor.load("/scratch/lgrinszt/lm_tab/AutogluonModels/ag-20240828_134101")
    ```

If you are not satisfied with the model, try to increase the training time,
adjust the hyperparameters (https://auto.gluon.ai/stable/tutorials/multimodal/advanced_topics/customization.html),
or post issues on GitHub (https://github.com/autogluon/autogluon/issues).

In [121]:
test_score = predictor.evaluate(test_data)
print(test_score)

INFO: SLURM auto-requeueing enabled. Setting signal handlers.

Predicting: |          | 0/? [00:00<?, ?it/s]

{'acc': 0.8208029197080292}

In [103]:
predictor.column_types

OrderedDict([('name', 'text'),
             ('artist', 'categorical'),
             ('danceability', 'numerical'),
             ('energy', 'numerical'),
             ('key', 'categorical'),
             ('loudness', 'numerical'),
             ('mode', 'categorical'),
             ('speechiness', 'numerical'),
             ('acousticness', 'numerical'),
             ('instrumentalness', 'numerical'),
             ('liveness', 'numerical'),
             ('valence', 'numerical'),
             ('tempo', 'numerical'),
             ('duration_ms', 'numerical'),
             ('time_signature', 'categorical'),
             ('chorus_hit', 'numerical'),
             ('sections', 'numerical'),
             ('target', 'categorical')])

In [114]:
predictor.feature_metadata.type_group_map_special

defaultdict(list,
            {'text': ['name_raw_text'],
             'bool': ['mode'],
             'text_as_category': ['name'],
             'text_special': ['name.char_count',
              'name.word_count',
              'name.capital_ratio',
              'name.lower_ratio',
              'name.digit_ratio',
              'name.special_ratio',
              'name.symbol_count..',
              'name.symbol_ratio..',
              'name.symbol_count.:',
              'name.symbol_ratio.:',
              'name.symbol_ratio. ',
              'name.symbol_count./',
              'name.symbol_ratio./',
              'name.symbol_count.-',
              'name.symbol_ratio.-'],
             'binned': ['name.char_count',
              'name.word_count',
              'name.capital_ratio',
              'name.lower_ratio',
              'name.digit_ratio',
              'name.special_ratio',
              'name.symbol_count..',
              'name.symbol_ratio..',
              'name.symbol_count.:',
              'name.symbol_ratio.:',
              'name.symbol_ratio. ',
              'name.symbol_count./',
              'name.symbol_ratio./',
              'name.symbol_count.-',
              'name.symbol_ratio.-'],
             'text_ngram': ['__nlp__.act',
              '__nlp__.all',
              '__nlp__.and',
              '__nlp__.away',
              '__nlp__.baby',
              '__nlp__.back',
              '__nlp__.be',
              '__nlp__.blues',
              '__nlp__.can',
              '__nlp__.de',
              '__nlp__.do',
              '__nlp__.don',
              '__nlp__.down',
              '__nlp__.el',
              '__nlp__.for',
              '__nlp__.from',
              '__nlp__.get',
              '__nlp__.girl',
              '__nlp__.go',
              '__nlp__.good',
              '__nlp__.got',
              '__nlp__.heart',
              '__nlp__.if',
              '__nlp__.ii',
              '__nlp__.in',
              '__nlp__.in the',
              '__nlp__.is',
              '__nlp__.it',
              '__nlp__.la',
              '__nlp__.let',
              '__nlp__.life',
              '__nlp__.like',
              '__nlp__.little',
              '__nlp__.live',
              '__nlp__.love',
              '__nlp__.man',
              '__nlp__.me',
              '__nlp__.metal',
              '__nlp__.mix',
              '__nlp__.my',
              '__nlp__.night',
              '__nlp__.no',
              '__nlp__.of',
              '__nlp__.of the',
              '__nlp__.on',
              '__nlp__.one',
              '__nlp__.out',
              '__nlp__.re',
              '__nlp__.remaster',
              '__nlp__.remastered',
              '__nlp__.rock',
              '__nlp__.she',
              '__nlp__.song',
              '__nlp__.that',
              '__nlp__.the',
              '__nlp__.this',
              '__nlp__.time',
              '__nlp__.to',
              '__nlp__.up',
              '__nlp__.version',
              '__nlp__.way',
              '__nlp__.we',
              '__nlp__.what',
              '__nlp__.with',
              '__nlp__.world',
              '__nlp__.you',
              '__nlp__.your',
              '__nlp__._total_']})

In [122]:
test_score = predictor.evaluate(test_data, metrics=['acc', 'f1', 'roc_auc'])
print(test_score)

INFO: SLURM auto-requeueing enabled. Setting signal handlers.

Predicting: |          | 0/? [00:00<?, ?it/s]

{'acc': 0.8208029197080292, 'f1': 0.8237827491326714, 'roc_auc': 0.8950061520595902}

In [116]:
predictor.leaderboard(test_data)

Load pretrained checkpoint: /scratch/lgrinszt/lm_tab/tmp/858df8f0b8214d2787eb5950ba486cc5-automm_sst/models/MultiModalPredictor/automm_model/model.ckpt
INFO: SLURM auto-requeueing enabled. Setting signal handlers.

Predicting: |          | 0/? [00:00<?, ?it/s]

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,0.895985,0.934,accuracy,8.628749,2.165288,190.895746,0.004103,0.000592,0.063075,2,True,8
1,CatBoost,0.872749,0.906,accuracy,0.128218,0.011640,5.795874,0.128218,0.011640,5.795874,1,True,3
2,XGBoost,0.838564,0.854,accuracy,0.104504,0.019260,1.413663,0.104504,0.019260,1.413663,1,True,4
3,MultiModalPredictor,0.836740,0.826,accuracy,8.302180,2.087936,170.555315,8.302180,2.087936,170.555315,1,True,7
4,LightGBMXT,0.835645,0.854,accuracy,0.073370,0.023265,3.589248,0.073370,0.023265,3.589248,1,True,2
5,LightGBM,0.835401,0.852,accuracy,0.070286,0.026433,4.967320,0.070286,0.026433,4.967320,1,True,1
6,LightGBMLarge,0.822506,0.846,accuracy,0.117298,0.018283,10.222701,0.117298,0.018283,10.222701,1,True,6
7,NeuralNetTorch,0.811314,0.828,accuracy,0.050591,0.015422,5.924915,0.050591,0.015422,5.924915,1,True,5

In [62]:
sentence1 = "it's a charming and often affecting journey."
sentence2 = "It's slow, very, very, very slow."
predictions = predictor.predict({'sentence': [sentence1, sentence2]})
print('"Sentence":', sentence1, '"Predicted Sentiment":', predictions[0])
print('"Sentence":', sentence2, '"Predicted Sentiment":', predictions[1])

ValueError: Dataframe columns `['sentence']` are detected, but columns `['name', 'acousticness', 'chorus_hit', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'sections', 'speechiness', 'tempo', 'valence', 'artist', 'key', 'mode', 'time_signature']` are missing. Please double check your input data to provide all the required columns `['name', 'acousticness', 'chorus_hit', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'sections', 'speechiness', 'tempo', 'valence', 'artist', 'key', 'mode', 'time_signature']`.

In [ ]:
probs = predictor.predict_proba({'sentence': [sentence1, sentence2]})
print('"Sentence":', sentence1, '"Predicted Class-Probabilities":', probs[0])
print('"Sentence":', sentence2, '"Predicted Class-Probabilities":', probs[1])

In [ ]:
test_predictions = predictor.predict(test_data)
test_predictions.head()

In [ ]:
embeddings = predictor.extract_embedding(test_data)
print(embeddings.shape)

In [ ]:
from sklearn.manifold import TSNE
X_embedded = TSNE(n_components=2, random_state=123).fit_transform(embeddings)
for val, color in [(0, 'red'), (1, 'blue')]:
    idx = (test_data['label'].to_numpy() == val).nonzero()
    plt.scatter(X_embedded[idx, 0], X_embedded[idx, 1], c=color, label=f'label={val}')
plt.legend(loc='best')

# Test pipeline

In [1]:
from src.data_loading import load_data
from skrub import MinHashEncoder
from sklearn.decomposition import PCA
from src.utils import FeaturesExtractor, FixedSizeSplit
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
#from tabpfn import TabPFNClassifier
import pandas as pd
import numpy as np
from tqdm import tqdm
from joblib import Parallel, delayed
import time
from sentence_transformers import SentenceTransformer
from src.encodings import encode_high_cardinality_features
from src.utils import run_on_encoded_data, FeaturesExtractor
from skrub import TableVectorizer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.random_projection import GaussianRandomProjection
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"
import submitit
from functools import partial
from itertools import product
import time
from autogluon.tabular import TabularDataset, TabularPredictor
from autogluon.multimodal import MultiModalPredictor
from autogluon.tabular.configs.hyperparameter_configs import get_hyperparameter_config

/scratch/lgrinszt/micromamba/envs/lm_tab/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
/scratch/lgrinszt/micromamba/envs/lm_tab/lib/python3.10/site-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(

In [2]:
%cd src

/scratch/lgrinszt/lm_tab/src

In [3]:
dataset = "clear_corpus"
n_test = 500
n_train = 500
features = "all"

X, y = load_data(dataset, max_rows=10000)
if len(X) < n_train + n_test:
    print("Not enough data")

Removed 0 columns with missing values on 18 columns
Removed 278 rows with missing values on 4724 rows
Removed 278 rows with missing values on 4446 rows
Removed 0 columns with missing values on 17 columns
New shape: (4446, 18)
Original task: regression for clear_corpus
Converting to binary classification
Classes (array([0, 1]), array([2223, 2223]))
X shape: (4446, 18), y shape: (4446,)

In [4]:
X

,Author,name,Pub_Year,Categ,Lexile_Band,Location,MPAA_Max,Google_WC,Sentence_Count,Paragraphs,Flesch-Reading-Ease,Flesch-Kincaid-Grade-Level,Automated_Readability_Index,SMOG_Readability,New_Dale-Chall_Readability_Formula,CAREC,CAREC_M,CML2RI
512,"Felix Simon, Christian Quade & Natascha Turetzek",The Process of Becoming a “Spider-Man”,2020,Info,1100,mid,G,158,10,1,65.81,8.06,8.47,10.0,7.19,0.14948,0.14819,15.998339
4280,H.W. Bodkinson,Warsaw Swamped With Refugees,1915,Info,1300,mid,PG,190,8,2,62.57,10.46,12.72,12.0,8.46,0.23585,0.21514,6.803592
2484,Lucian of Samosata,Lucian's True History,1894,Lit,900,mid,PG,163,3,1,43.21,20.73,25.13,10.0,8.66,0.09231,0.11811,18.526911
2721,Mr. JOHN GJERS,SOAKING PITS FOR STEEL INGOTS.,1882,Info,1500,mid,G,186,4,3,43.03,18.93,22.35,15.0,9.16,0.35081,0.33681,21.017523
960,Diana Alkire & Elizabeth Redcay,Understanding Other Minds: What Happens in Our...,2019,Info,1100,mid,G,151,8,2,44.51,11.77,12.05,13.0,8.84,0.20925,0.22531,9.790946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749,simple wiki,Physics,2020,Info,1100,mid,G,158,10,2,55.02,9.54,9.66,11.0,8.70,0.10082,0.10364,11.700335
437,simple wiki,Computer_program,2020,Info,900,start,PG,183,12,7,63.28,8.35,7.34,12.0,8.85,0.32220,0.30811,21.225827
491,"Elyse Boudin, Frédérique Carcaillet, Anne-Soph...",Coral Reef Fish: Not Just a Matter of Beauty!,2020,Info,1100,mid,G,162,9,1,52.79,10.37,11.12,13.0,9.01,0.24997,0.25254,15.413966
2189,"From The London Times, Nov. 25, 1914",RUMANIA’S CLAIMS,1914,Info,1300,mid,PG,198,10,3,39.12,12.80,13.08,14.0,10.05,0.34241,0.32437,3.833055
1672,Joanne Bloch (retold folktale),The smell thief,2014,Lit,900,mid,G,192,13,1,77.80,6.10,5.78,8.0,5.76,0.06540,0.05203,17.732384

In [5]:
encoding = "skrub__minhash_30"
X_enc, X_rest = encode_high_cardinality_features(X, encoding, dataset_name=dataset, override_cache=False, cardinality_threshold=30, fail_if_not_cached=True)
cv = FixedSizeSplit(n_splits=7, n_train=n_train, n_test=n_test, random_state=42)

numeric ['Google_WC', 'Sentence_Count', 'Paragraphs', 'Flesch-Reading-Ease', 'Flesch-Kincaid-Grade-Level', 'Automated_Readability_Index', 'SMOG_Readability', 'New_Dale-Chall_Readability_Formula', 'CAREC', 'CAREC_M', 'CML2RI']
low_cardinality ['Categ', 'Lexile_Band', 'Location', 'MPAA_Max']
high_cardinality ['Author', 'name', 'Pub_Year']
High cardinality columns ['Author', 'name', 'Pub_Year']
working dir /scratch/lgrinszt/lm_tab/src

FileNotFoundError: Cache not found for clear_corpus_Author_skrub__minhash_30.npy

In [7]:
from skrub import TableVectorizer

In [9]:
TableVectorizer()

TableVectorizer()