In [14]:
all_datasets = ['product_sentiment_machine_hack', 'jigsaw_unintended_bias', 'jigsaw_unintended_bias100K', 'google_qa_label', 'google_qa_answer_helpful', 'google_qa_answer_plausible', 'google_qa_answer_type_procedure', 'google_qa_answer_type_reason_explanation', 'google_qa_question_type_reason_explanation', 'google_qa_answer_satisfaction', 'women_clothing_review', 'melbourne_airbnb', 'mercari_price_suggestion', 'ae_price_prediction', 'mercari_price_suggestion100K', 'imdb_genre_prediction', 'fake_job_postings', 'kick_starter_funding', 'jc_penney_products', 'wine_reviews', 'news_popularity', 'news_channel', 'news_popularity2', 'fake_job_postings2', 'bookprice_prediction', 'data_scientist_salary', 'california_house_price']
benchmark_datasets = list(TEXT_BENCHMARK_ALIAS_MAPPING.values())

In [17]:
benchmark_datasets

['product_sentiment_machine_hack',
 'melbourne_airbnb',
 'news_channel',
 'wine_reviews',
 'imdb_genre_prediction',
 'jigsaw_unintended_bias100K',
 'fake_job_postings2',
 'kick_starter_funding',
 'ae_price_prediction',
 'google_qa_answer_type_reason_explanation',
 'google_qa_question_type_reason_explanation',
 'women_clothing_review',
 'mercari_price_suggestion100K',
 'jc_penney_products',
 'news_popularity2',
 'bookprice_prediction',
 'data_scientist_salary',
 'california_house_price']

In [164]:
list(TEXT_BENCHMARK_ALIAS_MAPPING.keys())

['prod',
 'airbnb',
 'channel',
 'wine',
 'imdb',
 'jigsaw',
 'fake',
 'kick',
 'ae',
 'qaa',
 'qaq',
 'cloth',
 'mercari',
 'jc',
 'pop',
 'book',
 'salary',
 'house']

In [163]:
from auto_mm_bench.datasets import TEXT_BENCHMARK_ALIAS_MAPPING, create_dataset

for alias in TEXT_BENCHMARK_ALIAS_MAPPING.keys():
    print(alias)
    dataset = create_dataset(TEXT_BENCHMARK_ALIAS_MAPPING[alias])
    data = dataset.data
    target_name = dataset.label_columns[0]
    features = dataset.feature_columns

    # Rename the target column to 'target' for the dataset
    data = data.rename(columns={target_name: "target"})

    # only keep the features and the target
    data = data[features + ["target"]]

    # save the dataset
    data.to_parquet(f"data/{alias}.parquet")
    print(data.shape)

prod
(5091, 3)
airbnb
(18316, 90)
channel
(20284, 18)
wine
(84123, 6)
imdb
(800, 12)
jigsaw
(100000, 31)
fake
(12725, 6)
kick
(86502, 10)
ae
(22662, 12)
qaa
(4863, 5)
qaq
(4863, 5)
cloth
(18788, 7)
mercari
(100000, 10)
jc
(10860, 6)
pop
(24007, 5)
book
(4989, 9)
salary
(15841, 7)
house
(37951, 40)

In [157]:
features

['Product_Description', 'Product_Type']

In [140]:
create_dataset(TEXT_BENCHMARK_ALIAS_MAPPING["qaa"]).data

,qa_id,question_title,question_body,question_user_name,question_user_page,answer,answer_user_name,answer_user_page,url,category,...,question_well_written,answer_helpful,answer_level_of_information,answer_plausible,answer_relevance,answer_satisfaction,answer_type_instructions,answer_type_procedure,answer_type_reason_explanation,answer_well_written
0,6803,Create Valid XML from XSD Loaded at Runtime (w...,\n Possible Duplicate:\n \n \n Programmati...,The How-To Geek,https://stackoverflow.com/users/291,For others that wound up here: the best soluti...,ginbot,https://stackoverflow.com/users/444803,http://stackoverflow.com/questions/2170614/cre...,STACKOVERFLOW,...,0.555556,0.888889,0.666667,1.000000,1.000000,0.933333,1.000000,0.333333,0.000000,1.000000
1,4199,"When enumerating motivations, is it correct to...",Suppose I am enumerating reasons not to fly. I...,gerrit,https://ell.stackexchange.com/users/55,This answer at ELU suggests:\n\n\n Both are c...,bytebuster,https://ell.stackexchange.com/users/27,http://ell.stackexchange.com/questions/886/fir...,CULTURE,...,1.000000,1.000000,0.666667,1.000000,1.000000,1.000000,0.000000,0.333333,1.000000,1.000000
2,1334,hard self collision: make particles occupy space,"By default, Blender's particles don't have any...",Ichthyo,https://blender.stackexchange.com/users/2615,There is an add on called Molecular. http://p...,Nathan Craddock,https://blender.stackexchange.com/users/5505,http://blender.stackexchange.com/questions/763...,TECHNOLOGY,...,0.666667,1.000000,0.666667,1.000000,0.888889,0.800000,0.333333,0.000000,0.333333,1.000000
3,869,Removing unwanted color from B&W image (aperture),I've been shooting ilford color-process b&amp;...,bmargulies,https://photo.stackexchange.com/users/11429,"If you want to remove all color, just slide th...",dpollitt,https://photo.stackexchange.com/users/4892,http://photo.stackexchange.com/questions/30375...,LIFE_ARTS,...,1.000000,0.888889,0.666667,1.000000,1.000000,1.000000,0.666667,0.333333,0.000000,1.000000
4,8616,Binary tree traversal without using recursion,Can anyone help to to create a binary tree and...,Sourajit Behera,https://stackoverflow.com/users/4713630,As pre-order can be done via depth-first searc...,Codor,https://stackoverflow.com/users/3355476,http://stackoverflow.com/questions/29264905/bi...,STACKOVERFLOW,...,0.555556,1.000000,0.555556,1.000000,1.000000,0.866667,1.000000,0.000000,0.000000,0.888889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4858,8296,Why are there so many different types of screw...,Newbie question.\n\nWhy is it that there's a b...,Doug T.,https://diy.stackexchange.com/users/321,I thought it would be useful to include an ima...,JYelton,https://diy.stackexchange.com/users/145,http://diy.stackexchange.com/questions/2701/wh...,LIFE_ARTS,...,1.000000,0.666667,0.333333,0.666667,0.666667,0.400000,0.000000,0.000000,1.000000,0.666667
4859,6478,DNS/MX issues arising when migrating Heroku ap...,I have a domain - myapp.com - hosted by Dream ...,tvalent2,https://serverfault.com/users/108346,Thats because you don't have a DNS entry for m...,Mark Henderson,https://serverfault.com/users/7709,http://serverfault.com/questions/353736,TECHNOLOGY,...,0.666667,1.000000,0.666667,1.000000,0.888889,0.866667,0.666667,0.333333,0.666667,0.777778
4860,2120,MS-Access VBA Date() works on one PC but not o...,I am designing my first database from the grou...,ctall,https://stackoverflow.com/users/5149553,I suspect the issue is user's region and langu...,Brian Cohan,https://stackoverflow.com/users/3447515,http://stackoverflow.com/questions/31596191/ms...,STACKOVERFLOW,...,1.000000,0.777778,0.777778,0.777778,1.000000,0.866667,0.666667,0.000000,1.000000,0.888889
4861,5497,When can an article be omitted?,"I am aware that articles are the modifiers, wh...",Flair,https://ell.stackexchange.com/users/8260,The examples given by the original poster are ...,Tᴚoɯɐuo,https://ell.stackexchange.com/users/10264,http://ell.stackexchange.com/questions/33304/w...,CULTURE,...,0.777778,0.777778,0.555556,1.000000,1.000000,0.733333,0.333333,0.000000,1.000000,1.000000
4862,5723,Does syncing more Google accounts decrease a p...,I recently got a Motorola Moto G (4.3 upgraded...,wrahool,https://android.stackexchange.com/users/55059,Short answer: yes and no.\n\nUsing three accou...,Dan Hulme,https://android.stackexchange.com/users/12442,http://android.stackexchange.com/questions/650...,TECHNOLOGY,...,0.888889,1.000000,0.666667,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.888889

In [158]:
from auto_mm_bench.datasets import dataset_registry
import pandas as pd

print(dataset_registry.list_keys())  # list of all dataset names
dataset_name = 'product_sentiment_machine_hack'

train_dataset = dataset_registry.create(dataset_name, 'train')
test_dataset = dataset_registry.create(dataset_name, 'test')

# Concatenate train and test datasets
combined_dataset = pd.concat([train_dataset.data, test_dataset.data], ignore_index=True)

to_remove = ["Unnamed: 0", "Text_ID"]
target_name = "Sentiment"

# Remove unnecessary columns
combined_dataset = combined_dataset.drop(columns=to_remove)

# Check for missing values
missing_values = combined_dataset.isnull().sum()
print("Missing values in each column:")
print(missing_values)

# Drop rows with missing target values
combined_dataset = combined_dataset.dropna(subset=[target_name])

# rename target name to target
combined_dataset = combined_dataset.rename(columns={target_name: "target"})

combined_dataset.to_parquet("data/product_sentiment_machine_hack.parquet")

['product_sentiment_machine_hack', 'jigsaw_unintended_bias', 'jigsaw_unintended_bias100K', 'google_qa_label', 'google_qa_answer_helpful', 'google_qa_answer_plausible', 'google_qa_answer_type_procedure', 'google_qa_answer_type_reason_explanation', 'google_qa_question_type_reason_explanation', 'google_qa_answer_satisfaction', 'women_clothing_review', 'melbourne_airbnb', 'mercari_price_suggestion', 'ae_price_prediction', 'mercari_price_suggestion100K', 'imdb_genre_prediction', 'fake_job_postings', 'kick_starter_funding', 'jc_penney_products', 'wine_reviews', 'news_popularity', 'news_channel', 'news_popularity2', 'fake_job_postings2', 'bookprice_prediction', 'data_scientist_salary', 'california_house_price']
Missing values in each column:
Product_Description    0
Product_Type           0
Sentiment              0
dtype: int64

In [159]:
combined_dataset

                                    Product_Description  Product_Type  target
0     #techcrunch #google This Post Has Nothing to d...             9       2
1     Data is the new oil. (Companies like Google an...             3       1
2     my sister is throwing the Google sxsw party to...             3       3
3     Clear +succinct visions make for great UX (thi...             9       2
4     40% of Google Maps use is mobile marissamayer ...             9       3
...                                                 ...           ...     ...
6359  is EVERYONE that works at google this genius??...             3       3
6360   Why the Apple pop-up shop at #SxSW sucks: {link}             2       1
6361  RT @mention RT @mention #iPad Lounge: Recharge...             9       2
6362  (via @mention #SXSW 2011: The #Google and #Bin...             9       2
6363  First tweet from a plane: Feedback for #Gogo. ...             9       2

[6364 rows x 3 columns]

In [75]:
from auto_mm_bench.datasets import dataset_registry
import pandas as pd

dataset_name = 'melbourne_airbnb'

train_dataset = dataset_registry.create(dataset_name, 'train')
test_dataset = dataset_registry.create(dataset_name, 'test')

# Concatenate train and test datasets
combined_dataset = pd.concat([train_dataset.data, test_dataset.data], ignore_index=True)

to_drop = ["last_scraped", "id", "last_scraped", "listing_url", "host_verifications", "price", "weekly_price", "monthly_price", "calendar_last_scraped", "requires_license", "license"]
# Find columns with only one unique value
columns_with_one_unique_value = [col for col in combined_dataset.columns if combined_dataset[col].nunique() == 1]
print(f"Columns with one unique value: {columns_with_one_unique_value}")
to_drop.extend(columns_with_one_unique_value)
columns_with_two_unique_values = [col for col in combined_dataset.columns if combined_dataset[col].nunique() == 2]
print(f"Columns with two unique values: {columns_with_two_unique_values}")

combined_dataset = combined_dataset.drop(columns=to_drop)

print(combined_dataset.shape)

target_name = "price_label"
combined_dataset = combined_dataset.rename(columns={target_name: "target"})

combined_dataset.to_parquet("data/melbourne_airbnb.parquet")
# I do get 89 features at the end, but I'm not sure they are the same than in the benchmark (the preprocessing script seeems imcomplete and fails for me)

Columns with one unique value: ['scrape_id', 'country_code', 'country', 'has_availability', 'requires_license']
Columns with two unique values: ['last_scraped', 'host_is_superhost', 'host_has_profile_pic', 'host_identity_verified', 'is_location_exact', 'calendar_last_scraped', 'instant_bookable', 'require_guest_profile_picture', 'require_guest_phone_verification', 'host_verifications_jumio', 'host_verifications_government_id', 'host_verifications_kba', 'host_verifications_zhima_selfie', 'host_verifications_facebook', 'host_verifications_work_email', 'host_verifications_google', 'host_verifications_sesame', 'host_verifications_manual_online', 'host_verifications_manual_offline', 'host_verifications_offline_government_id', 'host_verifications_selfie', 'host_verifications_reviews', 'host_verifications_identity_manual', 'host_verifications_sesame_offline', 'host_verifications_weibo', 'host_verifications_email', 'host_verifications_sent_id', 'host_verifications_phone']
(22895, 90)

In [76]:
import pandas as pd

dataset_name = 'news_channel'

train_dataset = dataset_registry.create(dataset_name, 'train')
test_dataset = dataset_registry.create(dataset_name, 'test')

# Concatenate train and test datasets
combined_dataset = pd.concat([train_dataset.data, test_dataset.data], ignore_index=True)

target_name = "channel"
combined_dataset = combined_dataset.rename(columns={target_name: "target"})

combined_dataset.to_parquet("data/news_channel.parquet")

In [80]:
dataset_name = 'wine_reviews'

train_dataset = dataset_registry.create(dataset_name, 'train')
test_dataset = dataset_registry.create(dataset_name, 'test')

# Concatenate train and test datasets
combined_dataset = pd.concat([train_dataset.data, test_dataset.data], ignore_index=True)
print(combined_dataset.shape)

target_name = "variety"
combined_dataset = combined_dataset.rename(columns={target_name: "target"})

combined_dataset.to_parquet("data/wine_reviews.parquet")

#TODO: check if I already have this dataset

(105154, 6)

In [83]:
dataset_name = 'imdb_genre_prediction'

train_dataset = dataset_registry.create(dataset_name, 'train')
test_dataset = dataset_registry.create(dataset_name, 'test')

# Concatenate train and test datasets
combined_dataset = pd.concat([train_dataset.data, test_dataset.data], ignore_index=True)
print(combined_dataset.shape)

target_name = "Genre_is_Drama"
combined_dataset = combined_dataset.rename(columns={target_name: "target"})

combined_dataset.to_parquet("data/imdb_genre_prediction.parquet")

(1000, 12)

In [110]:
dataset_name = 'jigsaw_unintended_bias100K'

train_dataset = dataset_registry.create(dataset_name, 'train')
test_dataset = dataset_registry.create(dataset_name, 'test')

# Concatenate train and test datasets
combined_dataset = pd.concat([train_dataset.data, test_dataset.data], ignore_index=True)
print(combined_dataset.shape)

to_remove = ["id", ]

(125000, 45)

In [111]:
combined_dataset

,id,target,comment_text,severe_toxicity,obscene,identity_attack,insult,threat,asian,atheist,...,article_id,rating,funny,wow,sad,likes,disagree,sexual_explicit,identity_annotator_count,toxicity_annotator_count
0,964172,False,The US and its allies have a 'nuanced' approac...,0.0,0.0,0.4,0.1,0.100000,0.0,0.0,...,166654,approved,0,0,0,0,0,0.0,5,10
1,5796506,True,No matter how undisciplined President Trump ap...,0.0,0.0,0.0,0.6,0.000000,NaN,NaN,...,368058,approved,0,0,0,1,0,0.0,0,10
2,702263,False,It's not a fait accompli that the Russians wer...,0.0,0.0,0.0,0.0,0.000000,NaN,NaN,...,156242,approved,2,0,1,4,0,0.0,0,4
3,5203876,False,They edited it. First there was an acknowledge...,0.0,0.0,0.0,0.0,0.000000,NaN,NaN,...,330427,approved,0,0,0,0,0,0.0,0,4
4,784869,False,Large and kind thanks to Tom Roberts for the b...,0.0,0.0,0.0,0.0,0.000000,NaN,NaN,...,159408,approved,0,0,0,3,0,0.0,0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124995,5488232,False,Not everyone can afford to live close to work ...,0.0,0.0,0.0,0.0,0.000000,NaN,NaN,...,349271,approved,0,0,0,0,0,0.0,0,4
124996,6283466,False,"""so in essence, those who drew their weapons h...",0.0,0.0,0.0,0.0,0.166667,NaN,NaN,...,396497,approved,0,0,0,0,0,0.0,0,6
124997,5459608,False,I hope the authors read these comments - the n...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,347373,approved,0,0,0,20,2,0.0,4,4
124998,4989352,False,Sr. Simone has male power too much on her mind...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,318103,approved,0,0,0,0,0,0.0,4,4
124999,5105646,False,A good column. In some ways I am glad that ac...,0.0,0.0,0.0,0.0,0.000000,NaN,NaN,...,325273,approved,0,0,0,5,5,0.0,0,4

In [97]:
dataset_name = 'fake_job_postings2'

train_dataset = dataset_registry.create(dataset_name, 'train')
test_dataset = dataset_registry.create(dataset_name, 'test')

# Concatenate train and test datasets
combined_dataset = pd.concat([train_dataset.data, test_dataset.data], ignore_index=True)
print(combined_dataset.shape)

target_name = "fraudulent"
combined_dataset = combined_dataset.rename(columns={target_name: "target"})

combined_dataset.to_parquet("data/fake_job_postings2.parquet")

(15907, 6)

In [103]:
dataset_name = 'kick_starter_funding'

train_dataset = dataset_registry.create(dataset_name, 'train')
test_dataset = dataset_registry.create(dataset_name, 'test')

# Concatenate train and test datasets
combined_dataset = pd.concat([train_dataset.data, test_dataset.data], ignore_index=True)
print(combined_dataset.shape)

target_name = "final_status"
combined_dataset = combined_dataset.rename(columns={target_name: "target"})

combined_dataset.to_parquet("data/kick_starter_funding.parquet")

(108128, 10)

In [121]:
dataset_name = 'ae_price_prediction'

train_dataset = dataset_registry.create(dataset_name, 'train')
test_dataset = dataset_registry.create(dataset_name, 'test')

# Concatenate train and test datasets
combined_dataset = pd.concat([train_dataset.data, test_dataset.data], ignore_index=True)
print(combined_dataset.shape)

target_name = "price"
combined_dataset = combined_dataset.rename(columns={target_name: "target"})

# Find columns with one unique value
unique_value_columns = [col for col in combined_dataset.columns if combined_dataset[col].nunique() == 1]
print(f"Columns with one unique value: {unique_value_columns}")
to_remove = ["mrp"]
to_remove.extend(unique_value_columns)

combined_dataset = combined_dataset.drop(columns=to_remove)

print(combined_dataset.shape)


combined_dataset.to_parquet("data/ae_price_prediction.parquet")

(28328, 14)
Columns with one unique value: ['retailer']
(28328, 12)

In [130]:
dataset_name = 'google_qa_answer_type_reason_explanation'

train_dataset = dataset_registry.create(dataset_name, 'train')
test_dataset = dataset_registry.create(dataset_name, 'test')

# Concatenate train and test datasets
combined_dataset = pd.concat([train_dataset.data, test_dataset.data], ignore_index=True)

to_keep = ['question_title', 'question_body', 'answer', 'category', "answer_type_reason_explanation"]
combined_dataset = combined_dataset[to_keep]

target_name = "answer_type_reason_explanation"
combined_dataset = combined_dataset.rename(columns={target_name: "target"})

combined_dataset.to_parquet("data/google_qa_answer_type_reason_explanation.parquet")

In [132]:
dataset_name = 'google_qa_question_type_reason_explanation'

train_dataset = dataset_registry.create(dataset_name, 'train')
test_dataset = dataset_registry.create(dataset_name, 'test')
    
# Concatenate train and test datasets
combined_dataset = pd.concat([train_dataset.data, test_dataset.data], ignore_index=True)

to_keep = ['question_title', 'question_body', 'question_type_reason_explanation']
combined_dataset = combined_dataset[to_keep]

target_name = "answer_type_reason_explanation"
combined_dataset = combined_dataset.rename(columns={target_name: "target"})

combined_dataset.to_parquet("data/google_qa_question_type_reason_explanation.parquet")

In [133]:
combined_dataset

,question_title,question_body,question_type_reason_explanation
0,Create Valid XML from XSD Loaded at Runtime (w...,\n Possible Duplicate:\n \n \n Programmati...,0.000000
1,"When enumerating motivations, is it correct to...",Suppose I am enumerating reasons not to fly. I...,0.333333
2,hard self collision: make particles occupy space,"By default, Blender's particles don't have any...",0.000000
3,Removing unwanted color from B&W image (aperture),I've been shooting ilford color-process b&amp;...,0.000000
4,Binary tree traversal without using recursion,Can anyone help to to create a binary tree and...,0.000000
...,...,...,...
6074,Install old version of Wine,Recording to this page https://appdb.winehq.or...,0.000000
6075,Planet orbits: what's the difference between g...,My physics teacher says that centripetal force...,1.000000
6076,"Using ""it's"" vs. using ""it is"" at the end of a...",\n Possible Duplicate:\n Is there some rule ...,0.666667
6077,Will this wall wart supply enough power?,I am building a little pen plotter.\n\nIt is p...,1.000000
6078,How can I superimpose LaTeX / TeX output over ...,I have a form as a PDF file. I would like to ...,0.000000

(array(['AEO', 'AERIE'], dtype=object), array([   24, 28304]))

In [119]:
combined_dataset

,product_name,mrp,target,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,Happy Unlined Bandeau Bra,26.95 USD,13.47,https://www.ae.com/aerie-happy-unlined-bandeau...,AERIE,Strapless Bras,Ae US,"Hello, Happy Bras. Happiness is feeling like t...",4.5,NaN,"[""Happiness from the inside out: light, comfy ...","[""32A"", ""32B"", ""32C"", ""34A"", ""34B"", ""34C"", ""34...","[""32B"", ""32C"", ""34B"", ""34C"", ""36B"", ""36D""]",Vanity Peach
1,Aerie Thong,9.50 USD,9.50,https://www.ae.com/undies-aerie-thong-dark-hea...,AERIE,Thongs,Ae US,Total cheek! The soft and comfy cotton you lov...,3.0,1.0,"[""Comfy, stretchy cotton"", ""Aerie undies: Your...","[""XS"", ""S"", ""M"", ""L"", ""XL"", ""XXL""]","[""XS"", ""L"", ""XL"", ""XXL""]",Navy
2,Katie Lightly Lined Bra,29.95 USD,17.97,https://www.ae.com/aerie-featured-katie-lightl...,AERIE,Katie,Ae US,The Girl Next Door The original t-shirt bra ev...,3.9,NaN,"[""Lightly lined"", ""Full coverage"", ""Underwire""...","[""30A"", ""30B"", ""30C"", ""30D"", ""32AA"", ""32A"", ""3...","[""30A"", ""30B"", ""30C"", ""30D"", ""32AA"", ""32A"", ""3...",White
3,Aerie Lace Sunnie Boybrief,14.50 USD,14.50,https://www.ae.com/aerie-lace-sunnie-boybrief-...,AERIE,Undies,Ae US,We're serious about soft. The Real Soft® fabri...,NaN,NaN,"[""Real Soft® fabric"", ""Low rise"", ""No cheek pe...","[""XS"", ""S"", ""M"", ""L"", ""XL"", ""XXL""]","[""XS"", ""S"", ""L"", ""XL"", ""XXL""]",Light Blue
4,Aerie Boybrief,9.50 USD,9.50,https://www.ae.com/featured-aerie-boybrief-tru...,AERIE,Boybriefs,Ae US,Our #1 fit. The soft and comfy cotton you love...,NaN,NaN,"[""Comfy, stretchy cotton"", ""Low rise"", ""No che...","[""XS"", ""S"", ""M"", ""L"", ""XL"", ""XXL""]","[""S""]",Current Coral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28323,Aerie Boyshort,9.50 USD,9.50,https://www.ae.com/featured-aerie-boyshort-dee...,AERIE,Everyday Loves Undies 6 for $26 USD,Ae US,Boy oh boy! The soft and comfy cotton you love...,NaN,NaN,"[""Comfy, stretchy cotton"", ""Aerie undies: Your...","[""XS"", ""S"", ""M"", ""L"", ""XL"", ""XXL""]","[""XS"", ""S"", ""M"", ""L"", ""XXL""]",Deep Plum
28324,Aerie Seamless Boybrief,12.50 USD,12.50,https://www.ae.com/aerie-seamless-boybrief-lig...,AERIE,Boybriefs,Ae US,Our #1 fit. Smooth: No seams. All comfort. Rea...,4.3,NaN,"[""Smooth seamless fabric"", ""Low rise"", ""No che...","[""XS"", ""S"", ""M"", ""L"", ""XL"", ""XXL""]","[""XXL""]",Pink Tint
28325,Aerie Boybrief,9.50 USD,9.50,https://www.ae.com/aerie-boybrief-valentine/ae...,AERIE,Boybriefs,Ae US,We'll keep this brief. It all started with a b...,NaN,NaN,"[""Comfy cotton"", ""Low rise"", ""No cheek peek"", ...","[""XS"", ""S"", ""M"", ""L"", ""XL"", ""XXL""]","[""XS"", ""S"", ""M"", ""L"", ""XL"", ""XXL""]",Valentine
28326,Happy Unlined Plunge Bra,29.95 USD,17.97,https://www.ae.com/aerie-happy-unlined-plunge-...,AERIE,Plunge,Ae US,"Hello, Happy Bras. Happiness is feeling like t...",4.4,63.0,"[""Happiness from the inside out: light mesh in...","[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...","[""32A"", ""32B"", ""32C"", ""34A"", ""34B"", ""34C"", ""34...",Be Pretty
28327,Aerie Hi-Neck Lace Trim Bralette,34.95 USD,20.97,https://www.ae.com/aerie-hi-neck-lace-trim-bra...,AERIE,Bralettes,Ae US,¡Amor! New bralettes. Get bralette happy. This...,NaN,NaN,"[""Shine fabric + guipure lace trim"", ""Crop sil...","[""XS"", ""S"", ""M"", ""L"", ""XL""]","[""XS"", ""S"", ""M"", ""L"", ""XL""]",Softest Jade